# Generated by Django 5.2.7 on 2025-11-12 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='monitor.client'),
            preserve_default=False,
        ),
    ]
