# Generated by Django 5.2.7 on 2025-11-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alert_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='ip_destination',
            field=models.GenericIPAddressField(default='192.168.0.17'),
            preserve_default=False,
        ),
    ]
